### ISSUE TITLE
C'est quoi ceci?

### ISSUE THREAD

**Issue by pascalfares** [Ibrahim-Keyrouz/SMB215#1]
Je n'ai pas très bien compris pourquoi ceci?

**Comment by Ibrahim-Keyrouz** [comment]
Dr @pascalfares , This project will be an android application that scans the barcodes of the products when they arrive from the supplier. An sqlite will help us insert every scanned product then a button in the application will do the transfer to the database using a POST method from REST web service.

**Comment by Ibrahim-Keyrouz** [comment]
Dr @pascalfares  all done with this issue ?

**Comment by pascalfares** [comment]
ok

**Comment by pascalfares** [comment]
decrire qurlque part soit dans teadme soit doc soit wiki
