### ISSUE TITLE
Issue in refreshing Restful web service

### ISSUE THREAD

**Issue by Ibrahim-Keyrouz** [Ibrahim-Keyrouz/SMB215#2]
Bjr Dr @pascalfares , 

I am having an issue in refreshing the web service : for example : 

I have a table "X". if this table is updated by J2EE application using the JSF framework the "find" method in the Restful web service keep returning the old data as if something is not refreshed .. Is there any tags or methods that I have to add to the Restful Project ?

**Comment by pascalfares** [comment]
Oui JPA un entity manager qui utilise un cache. Si tu change les valeurs dans la BD depuis un autre entitymanager tu auras un problème de cache.

Il faut soit vider le cache.

soit utiliser tom propre entity manager

voir cet exemple https://github.com/pascalfares/smb215-15/tree/master/Portique/portique

EN plus ce projet fonctionne avec des serveur d'application sans EJB comme tomcat8 par exemple

**Comment by Ibrahim-Keyrouz** [comment]
Hello Dr @pascalfares , 

Tx a lot for ur help, I added this line of code to my Restful Method : 
em.getEntityManagerFactory().getCache().evictAll();

And everything is working perfectly ... I consider this issue as closed

**Comment by pascalfares** [comment]
Tu devrais aussi pouvoir configurer le cache dans persitence.xml

Pascal Fares
http://www.cofares.net
Le 19 juin 2015 23:04, "Ibrahim Keyrouz" notifications@github.com a
écrit :

**Comment by Ibrahim-Keyrouz** [comment]
I added those two lines to the persistence.xml to clear the cache : 

<properties>
     <property name="eclipselink.query-results-cache" value="false"/>
     <property name="eclipselink.cache.shared.default" value="false"/>
 </properties>

And everything is working perfectly
Tx Dr. 

Plz notify me If this is the solution to close the issue.

**Comment by Ibrahim-Keyrouz** [comment]
I added those two lines to the persistence.xml to clear the cache : 

```
 <property name="eclipselink.query-results-cache" value="false"/>
 <property name="eclipselink.cache.shared.default" value="false"/>
```

And everything is working perfectly
Tx Dr. 

Plz notify me If this is the solution to close the issue.

**Comment by Ibrahim-Keyrouz** [comment]
N.B : I had to add the tag to my entity class : 

@Cacheable(false)
