### ISSUE TITLE
Issue in calling a url in web service

### ISSUE THREAD

**Issue by Ibrahim-Keyrouz** [Ibrahim-Keyrouz/SMB215#3]
Hello Dr @pascalfares 

I've created a web service from an entity that has a composite Primary Key (docid,barcode)

I found the solution to call the GET method (find{id}  for example) : 
http://localhost:8080/STK_PRD_WS/webresources/entities.purchasesdtl/somePath;docid=123456;barcode=4010127420007

BUT is there a solution to only pass the docid parameter  ? Y ? because I want all the records having a specific docid from the recept_dtl (NB primary key is (docid,barcode))

I've tried : http://localhost:8080/STK_PRD_WS/webresources/entities.purchasesdtl/somePath;docid=123456
But the result was " no content "

The solution is a way in calling the URI or I have to make a new method ?

**Comment by pascalfares** [comment]
uri/docid/barcode
@path(uri/{docid}/{barcode})

Pascal Fares
http://www.cofares.net
Le 25 juin 2015 11:41, "Ibrahim Keyrouz" notifications@github.com a
écrit :

**Comment by Ibrahim-Keyrouz** [comment]
Hello Dr @pascalfares  

Je veux tous les barcodes correpondant a un docid specfique. par example : **uri/somePath;docid=123456**

NB que **uri/somePath;docid=123456;barcode=4010127420007** me retourne un vrai resultat ce qui est l'entité dont le docid = 123456 et ayant un barcode=4010127420007..

NB  que dans la methode find({id}) on appelle la methode getPrimaryKey(id) ce qui implique que le PathSegment id doit etre le couple (docid,barcode) 

This is the code : 

@GET
    @Path("{id}")
    @Produces({"application/json"})
    public PurchasesDtl **find**(@PathParam("id") PathSegment id) {

```
    entities.PurchasesDtlPK key = getPrimaryKey(id);
    return super.find(key);
}
```

private PurchasesDtlPK **getPrimaryKey**(PathSegment pathSegment) {
        /*
         \* pathSemgent represents a URI path segment and any associated matrix parameters.
         \* URI path part is supposed to be in form of 'somePath;docid=docidValue;barcode=barcodeValue'.
         \* Here 'somePath' is a result of getPath() method invocation and
         \* it is ignored in the following code.
         \* Matrix parameters are used as field names to build a primary key instance.
         */
        entities.PurchasesDtlPK key = new entities.PurchasesDtlPK();
        javax.ws.rs.core.MultivaluedMap<String, String> map = pathSegment.getMatrixParameters();
        java.util.List<String> docid = map.get("docid");
        if (docid != null && !docid.isEmpty()) {
            key.setDocid(docid.get(0));
        }
        java.util.List<String> barcode = map.get("barcode");
        if (barcode != null && !barcode.isEmpty()) {
            key.setBarcode(barcode.get(0));
        }
        return key;
    }

**Comment by pascalfares** [comment]
quand tu a généré les entity tu a une named query findByXxx pour chacun des
champs de l'entity. sinon tu peut ecrire cette requete.. dans mes tutoruals
il y a plusieurs exemples

Pascal Fares
http://www.cofares.net
Le 28 juin 2015 16:43, "Ibrahim Keyrouz" notifications@github.com a
écrit :

**Comment by pascalfares** [comment]
n'utilise pas queryqparam mais querypath. queryparam ce n'est pas élégant.

Pascal Fares
http://www.cofares.net
Le 28 juin 2015 16:43, "Ibrahim Keyrouz" notifications@github.com a
écrit :
