### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Ibrahim-Keyrouz** [Ibrahim-Keyrouz/SMB215#4]
Hello Dr @pascalfares ,

I want you to give me an advice about : 

If I have a field (flag) in a table (Purchase) that I want it to be updated after an insert in another table (Recept) : Is it more efficient to call a web service that update this field OR to do a trigger in the Database ? 

NB : The inserting in the table Recept will be from the Android App only 

Best Regards.

**Comment by pascalfares** [comment]
Un trigger a une utilisation différente de "l'applicatif"

Le trigger c'est plutot pour l'intégrité des données, ne soit pas être
utiliser pour du "fonctionnel" de plus qur ce passe t'il le jour ou tu
utilise une BD sans trigger?!

_____
_Il est toujours préférable de trouver une solution que de produire des
excuses_
_Pascal Fares http://www.cofares.net_

Enseignant ISAE - Cnam Liban
Chef du département informatique http://depinfo.isae.edu.lb Cnam Liban

2015-07-01 15:42 GMT+03:00 Ibrahim Keyrouz notifications@github.com:

**Comment by Ibrahim-Keyrouz** [comment]
Hehe, je suis un peu accro à la base de données Oracle :+1: 

NB : J'ai creer dans ma BD la table "STK_TRS" pour etre remplie avec chaque transaction faite sur les autres tables suivant un Trigger dans la BD pour  l'intégrité des données.

Merci
